import { StyleSheet } from "react-native";
import {
  BRAND_DANGER,
  brandDangerBg,
  brandDangerBorder,
  neutral,
  statusBadgeBg,
} from "../../../../shared/theme/color";
import { appTypography } from "../../../../shared/utils/typography";

export const tenantItemDescriptionStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: neutral.backgroundSubtle },
  scrollContent: { padding: 16, paddingTop: 12 },
  descriptionCard: {
    backgroundColor: neutral.surface,
    borderRadius: 12,
    padding: 16,
  },
  descriptionTitle: {
    ...appTypography.cardTitle,
    fontWeight: "600",
    color: neutral.text,
    marginBottom: 16,
  },
  descriptionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: neutral.background,
  },
  descriptionRowLast: { borderBottomWidth: 0 },
  descriptionLabel: {
    ...appTypography.labelRow,
    color: neutral.textSecondary,
    flex: 0.35,
  },
  descriptionValue: {
    ...appTypography.labelRowValue,
    color: neutral.text,
    flex: 0.65,
  },
  descriptionStatusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  descriptionStatusAvailable: { backgroundColor: statusBadgeBg.available },
  descriptionStatusInUse: { backgroundColor: statusBadgeBg.inUse },
  descriptionStatusDisposed: { backgroundColor: statusBadgeBg.disposed },
  /** Trạng thái hỏng — nhấn mạnh hơn thanh lý. */
  descriptionStatusBroken: {
    backgroundColor: brandDangerBg,
    borderWidth: 1,
    borderColor: brandDangerBorder,
  },
  descriptionStatusOther: { backgroundColor: neutral.background },
  descriptionEditBtn: {
    marginTop: 20,
    backgroundColor: BRAND_DANGER,
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
  },
  descriptionEditBtnContentRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  descriptionEditBtnText: {
    ...appTypography.dialogButton,
    color: neutral.surface,
  },
  errorBanner: {
    backgroundColor: brandDangerBg,
    padding: 12,
    marginHorizontal: 16,
    marginTop: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: brandDangerBorder,
  },
  errorBannerText: {
    ...appTypography.secondary,
    color: BRAND_DANGER,
    fontWeight: "500",
  },
  imagesSection: {
    marginTop: 14,
  },
  imagesLabel: {
    ...appTypography.labelRow,
    color: neutral.textSecondary,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    marginBottom: 10,
  },
  imagesHint: {
    ...appTypography.secondary,
    color: neutral.textSecondary,
    fontStyle: "italic",
  },
  imageGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    paddingVertical: 6,
  },
  imageStrip: {
    flexDirection: "row",
    gap: 10,
    paddingVertical: 6,
    paddingHorizontal: 2,
  },
  imageStripScroll: {
    maxHeight: 170,
  },
  imageThumb: {
    width: "48%",
    aspectRatio: 1,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: neutral.borderMuted ?? neutral.border,
    backgroundColor: neutral.background,
  },
  imageThumbHorizontal: {
    width: 150,
    aspectRatio: 1,
  },
  imageMoreBtn: {
    marginTop: 8,
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: neutral.borderMuted ?? neutral.border,
    backgroundColor: neutral.background,
  },
  imageMoreBtnText: {
    ...appTypography.secondary,
    fontWeight: "600",
    color: neutral.textSecondary,
  },
  imageThumbImg: {
    width: "100%",
    height: "100%",
  },
  imageModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.85)",
    padding: 16,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  imageModalBackdropDismiss: {
    ...StyleSheet.absoluteFillObject,
  },
  imageModalContent: {
    width: "100%",
    height: "82%",
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "#0b1220",
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.25)",
    zIndex: 1,
  },
  imageModalPager: {
    width: "100%",
    flex: 1,
  },
  imageModalClose: {
    position: "absolute",
    top: 10,
    right: 10,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(2, 6, 23, 0.6)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  imageModalCloseText: {
    color: "#fff",
    fontSize: 22,
    fontWeight: "800",
    lineHeight: 24,
  },
  imageModalImage: {
    width: "100%",
    height: "100%",
  },
});
