import { StyleSheet } from "react-native";
import {
  BRAND_DANGER,
  brandBlueMutedBg,
  brandBlueMutedBorder,
  brandDangerBg,
  brandDangerBorder,
  brandPrimary,
  brandSecondary,
  brandTintBg,
  neutral,
} from "../../../../shared/theme/color";
import { appTypography } from "../../../../shared/utils/typography";

export const ticketStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: neutral.canvasMuted,
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    padding: 20,
    paddingBottom: 40,
    gap: 16,
  },
  backButton: {
    marginBottom: 20,
  },
  backButtonText: {
    ...appTypography.dialogButton,
    color: neutral.text,
  },
  title: {
    ...appTypography.ticketScreenTitle,
    marginBottom: 24,
    color: neutral.text,
  },
  pageIntro: {
    marginTop: -4,
    marginBottom: 4,
    paddingHorizontal: 2,
  },
  pageIntroText: {
    fontSize: 14,
    lineHeight: 20,
    color: neutral.textSecondary,
  },
  sectionBlock: {
    marginBottom: 0,
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.6,
    color: neutral.textMuted,
    textTransform: "uppercase",
    marginBottom: 10,
    marginLeft: 2,
  },
  deviceInfoSection: {
    marginBottom: 0,
  },
  sectionTitle: {
    ...appTypography.cardTitle,
    fontWeight: "600",
    marginBottom: 12,
    color: neutral.text,
  },
  deviceInfoCard: {
    backgroundColor: neutral.surface,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: neutral.border,
    shadowColor: neutral.slate900,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  deviceInfoLabel: {
    ...appTypography.labelRow,
    color: neutral.textMuted,
    marginBottom: 6,
    fontWeight: "600",
  },
  deviceInfoValue: {
    ...appTypography.modalListItem,
    fontWeight: "600",
    color: neutral.text,
    fontSize: 16,
    lineHeight: 22,
  },
  formSection: {
    backgroundColor: neutral.surface,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: neutral.border,
    shadowColor: neutral.slate900,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 1,
    gap: 2,
  },
  inputGroup: {
    marginBottom: 18,
  },
  inputGroupLast: {
    marginBottom: 0,
  },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: neutral.text,
    marginBottom: 8,
  },
  labelRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  labelRowLeft: {
    fontSize: 14,
    fontWeight: "600",
    color: neutral.text,
    flexShrink: 1,
  },
  charCount: {
    fontSize: 12,
    fontWeight: "500",
    color: neutral.textMuted,
    marginLeft: 8,
  },
  required: {
    color: BRAND_DANGER,
  },
  input: {
    borderWidth: 1,
    borderColor: neutral.inputBorder,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 13,
    ...appTypography.dialogButton,
    fontWeight: "400",
    color: neutral.text,
    backgroundColor: neutral.canvasMuted,
  },
  textArea: {
    minHeight: 132,
    paddingTop: 14,
  },
  imagesSection: {
    marginBottom: 0,
  },
  imagesHint: {
    marginTop: 0,
    marginBottom: 12,
    fontSize: 13,
    lineHeight: 18,
    color: neutral.textMuted,
  },
  attachmentDropzone: {
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: neutral.border,
    borderRadius: 14,
    padding: 14,
    backgroundColor: neutral.canvasMuted,
    marginBottom: 12,
  },
  imageButtonsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 0,
    marginBottom: 4,
  },
  imageButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: brandPrimary,
    backgroundColor: brandPrimary,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 12,
  },
  imageButtonSecondary: {
    backgroundColor: neutral.surface,
    borderColor: neutral.inputBorder,
  },
  imageButtonText: {
    ...appTypography.dialogButton,
    fontWeight: "700",
    color: neutral.surface,
    fontSize: 14,
  },
  imageButtonTextSecondary: {
    color: neutral.textSecondary,
    fontWeight: "600",
  },
  imageLibraryLink: {
    marginTop: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  imageLibraryLinkText: {
    ...appTypography.dialogButton,
    fontWeight: "600",
    color: brandPrimary,
    textDecorationLine: "underline",
  },
  imageGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  imageThumb: {
    width: "48%",
    aspectRatio: 1,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: neutral.borderMuted ?? neutral.border,
    backgroundColor: neutral.canvasMuted,
  },
  imageThumbInner: {
    flex: 1,
    width: "100%",
  },
  imageThumbImg: {
    width: "100%",
    height: "100%",
  },
  removeImageBtn: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(15, 23, 42, 0.78)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  removeImageBtnText: {
    color: neutral.surface,
    fontSize: 12,
    fontWeight: "800",
  },
  ticketImagesScroll: {
    maxHeight: 170,
  },
  ticketImagesStrip: {
    flexDirection: "row",
    gap: 10,
    paddingVertical: 4,
    paddingHorizontal: 2,
  },
  ticketImageThumbHorizontal: {
    width: 150,
    aspectRatio: 1,
  },
  ticketImagesMoreBtn: {
    marginTop: 8,
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: neutral.borderMuted ?? neutral.border,
    backgroundColor: neutral.canvasMuted,
  },
  ticketImagesMoreBtnText: {
    fontSize: 12,
    fontWeight: "600",
    color: neutral.textSecondary,
  },
  priorityContainer: {
    flexDirection: "row",
    gap: 8,
    marginTop: 8,
  },
  priorityButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: neutral.inputBorder,
    backgroundColor: neutral.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  priorityButtonActive: {
    backgroundColor: brandSecondary,
    borderColor: brandSecondary,
  },
  priorityButtonText: {
    ...appTypography.body,
    fontWeight: "500",
    color: neutral.textSecondary,
    textAlign: "center",
  },
  priorityButtonTextActive: {
    color: neutral.surface,
    textAlign: "center",
  },
  submitButton: {
    backgroundColor: brandPrimary,
    borderRadius: 14,
    paddingVertical: 16,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
    minHeight: 52,
    shadowColor: brandPrimary,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.22,
    shadowRadius: 4,
    elevation: 5,
  },
  submitButtonText: {
    color: neutral.surface,
    ...appTypography.dialogButton,
    fontWeight: "700",
  },
  /** Switch loại ticket — cùng pattern với ConsumptionScreen (điện / nước). */
  typeSwitchTrack: {
    flexDirection: "row",
    backgroundColor: neutral.canvasMuted,
    borderRadius: 25,
    padding: 3,
    borderWidth: 1,
    borderColor: neutral.border,
    position: "relative",
    overflow: "hidden",
  },
  typeSwitchIndicator: {
    position: "absolute",
    top: 3,
    left: 3,
    bottom: 3,
    borderRadius: 22,
  },
  typeSwitchTab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    gap: 6,
    zIndex: 1,
  },
  typeSwitchTabText: {
    fontSize: 14,
    fontWeight: "600",
    color: neutral.textSecondary,
  },
  typeSwitchTabTextActive: {
    color: "#fff",
  },
});

/** Chọn thiết bị (modal tìm kiếm) — dùng chung trên màn Ticket khi không có presetAsset. */
export const ticketAssetSelectStyles = StyleSheet.create({
  trigger: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: neutral.inputBorder,
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 14,
    backgroundColor: neutral.surface,
    gap: 10,
  },
  triggerText: {
    ...appTypography.dialogButton,
    fontWeight: "500",
    color: neutral.text,
    flex: 1,
  },
  triggerPlaceholder: {
    color: neutral.textMuted,
    fontWeight: "400",
  },
  modalRoot: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(15, 23, 42, 0.45)",
  },
  sheet: {
    backgroundColor: neutral.surface,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: "88%",
    paddingBottom: 8,
    borderWidth: 1,
    borderColor: neutral.border,
    borderBottomWidth: 0,
  },
  sheetHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: neutral.border,
  },
  sheetTitle: {
    ...appTypography.cardTitle,
    fontWeight: "700",
    color: neutral.text,
  },
  searchWrap: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: neutral.inputBorder,
    paddingHorizontal: 12,
    backgroundColor: neutral.canvasMuted,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 10,
    ...appTypography.dialogButton,
    color: neutral.text,
  },
  list: {
    flexGrow: 0,
    maxHeight: 360,
  },
  assetRow: {
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: neutral.border,
  },
  assetRowBroken: {
    backgroundColor: brandDangerBg,
    borderLeftWidth: 4,
    borderLeftColor: brandDangerBorder,
  },
  assetRowTitle: {
    ...appTypography.modalListItem,
    fontWeight: "600",
    color: neutral.text,
  },
  assetRowTitleBroken: {
    color: BRAND_DANGER,
  },
  assetRowSub: {
    ...appTypography.labelRow,
    color: neutral.textMuted,
    marginTop: 4,
  },
  emptyText: {
    ...appTypography.body,
    color: neutral.textMuted,
    textAlign: "center",
    paddingVertical: 28,
    paddingHorizontal: 24,
  },
  loadingBox: {
    paddingVertical: 32,
    alignItems: "center",
  },
});

/** Bottom sheet menu (+) trên danh sách ticket. */
export const tenantTicketMenuStyles = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.45)",
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: neutral.surface,
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    paddingHorizontal: 20,
    paddingTop: 12,
    borderWidth: 1,
    borderColor: neutral.border,
    borderBottomWidth: 0,
  },
  grab: {
    alignSelf: "center",
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: neutral.border,
    marginBottom: 16,
  },
  menuTitle: {
    ...appTypography.cardTitle,
    fontWeight: "700",
    color: neutral.text,
    marginBottom: 6,
  },
  menuSubtitle: {
    ...appTypography.body,
    color: neutral.textSecondary,
    marginBottom: 20,
    lineHeight: 22,
  },
  primaryBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: brandSecondary,
    borderRadius: 14,
    paddingVertical: 16,
    marginBottom: 10,
  },
  primaryBtnText: {
    ...appTypography.dialogButton,
    fontWeight: "700",
    color: neutral.surface,
  },
  ghostBtn: {
    alignItems: "center",
    paddingVertical: 14,
    marginBottom: 4,
  },
  ghostBtnText: {
    ...appTypography.dialogButton,
    fontWeight: "600",
    color: neutral.textSecondary,
  },
});

/** Màn danh sách ticket tenant (TenantTicketList) — UI card nhẹ, ít màu. */
export const tenantTicketListStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: neutral.canvasMuted,
  },
  pageHeading: {
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 14,
  },
  pageTitle: {
    ...appTypography.ticketScreenTitle,
    fontSize: 22,
    color: neutral.heading,
    marginBottom: 6,
  },
  pageSubtitle: {
    fontSize: 13,
    lineHeight: 18,
    color: neutral.textMuted,
  },
  listContent: {
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 8,
    gap: 12,
  },
  listEmptyGrow: {
    flexGrow: 1,
    justifyContent: "center",
  },
  /**
   * Vùng bọc thanh lọc — nền canvas; thẻ trắng bên trong giống các card trong list.
   */
  filterSectionWrap: {
    zIndex: 10,
    elevation: 0,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 4,
  },
  /** Khung trắng cùng hệ với thẻ ticket (`card`). */
  filterCard: {
    backgroundColor: neutral.surface,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: neutral.border,
    shadowColor: neutral.slate900,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    marginBottom: 8,
  },
  filterCardIntro: {
    marginBottom: 12,
    gap: 4,
  },
  filterCardTitle: {
    ...appTypography.listTitle,
    color: neutral.heading,
    fontWeight: "800",
  },
  filterCardSubtitle: {
    fontSize: 13,
    lineHeight: 18,
    color: neutral.textMuted,
    fontWeight: "500",
  },
  filterChipsScroll: {
    marginHorizontal: -2,
  },
  filterChipsContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 2,
    paddingRight: 8,
  },
  /** Chip lọc — cùng logic với NotificationScreen (`sectionTab`). */
  filterSortChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: neutral.slate200,
    backgroundColor: neutral.canvasMuted,
  },
  filterSortChipActive: {
    borderColor: brandPrimary,
    backgroundColor: brandTintBg,
  },
  filterSortChipText: {
    fontSize: 13,
    fontWeight: "700",
    color: neutral.slate700,
  },
  filterSortChipTextActive: {
    color: brandSecondary,
  },
  /** FAB (+) góc dưới phải — tạo ticket mới. */
  fab: {
    position: "absolute",
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: brandPrimary,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 20,
    shadowColor: neutral.slate900,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 12,
  },
  card: {
    backgroundColor: neutral.surface,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: neutral.border,
    shadowColor: neutral.slate900,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  /** Hàng meta: loại ticket (trái) + giờ & trạng thái chữ (phải). */
  metaHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  headerRightCol: {
    alignItems: "flex-end",
    flexShrink: 1,
    gap: 2,
  },
  /** Trạng thái + chevron (ví dụ chờ duyệt báo giá) — một hàng, không khung phụ. */
  headerStatusRowEnd: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 4,
    maxWidth: "100%",
  },
  headerTimeText: {
    fontSize: 12,
    fontWeight: "500",
    color: neutral.textMuted,
  },
  /** Màu gán trong component theo trạng thái (đỏ thanh toán / teal đang xử lý). */
  headerStatusEmphasis: {
    fontSize: 13,
    fontWeight: "700",
    textAlign: "right",
    flexShrink: 1,
    minWidth: 0,
  },
  contentRowThumb: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  thumbImage: {
    width: 72,
    height: 72,
    borderRadius: 10,
  },
  /** Giữ đúng 72×72 như ảnh — không icon, không viền (chỗ trống căn chỉnh layout). */
  thumbSpacer: {
    width: 72,
    height: 72,
    borderRadius: 10,
  },
  contentTextCol: {
    flex: 1,
    minWidth: 0,
  },
  typeTagOnCard: {
    alignSelf: "flex-start",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    marginBottom: 8,
  },
  typeTagInMeta: {
    marginBottom: 0,
    flexShrink: 1,
    maxWidth: "58%",
  },
  typeTagOnCardText: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.4,
  },
  cardTitleFigma: {
    fontSize: 16,
    fontWeight: "700",
    color: neutral.text,
    lineHeight: 22,
    marginBottom: 0,
  },
  dividerThin: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: neutral.border,
    marginTop: 14,
    marginBottom: 12,
  },
  costEstimateRow: {
    alignItems: "flex-end",
    marginBottom: 12,
  },
  costEstimateLabel: {
    fontSize: 13,
    color: neutral.textSecondary,
  },
  costEstimateAmount: {
    fontSize: 14,
    fontWeight: "800",
    color: neutral.text,
  },
  progressInset: {
    marginTop: 4,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    padding: 12,
    borderRadius: 12,
    backgroundColor: neutral.tileMuted ?? "#F1F5F9",
    borderWidth: 1,
    borderColor: neutral.border,
  },
  progressInsetTextCol: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  progressInsetTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: neutral.text,
  },
  progressInsetSub: {
    fontSize: 12,
    lineHeight: 17,
    color: neutral.textMuted,
  },
  /** Ô gợi ý trong thẻ chờ duyệt báo giá — cùng layout progressInset, tone cam hòa với card. */
  progressInsetQuoteApprove: {
    marginTop: 4,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    padding: 12,
    borderRadius: 12,
    backgroundColor: "rgba(245, 158, 11, 0.14)",
    borderWidth: 1,
    borderColor: "rgba(217, 119, 6, 0.25)",
  },
  progressInsetTitleQuoteApprove: {
    fontSize: 13,
    fontWeight: "700",
    color: "#92400E",
    lineHeight: 19,
  },
  /** Card cần thanh toán — nền trắng; trạng thái đỏ theo mockup. */
  cardAwaitingPayment: {
    borderColor: "rgba(220, 38, 38, 0.25)",
  },
  /** Ticket chờ duyệt báo giá — nền kem đục + viền cùng gam (tránh lớp trong loang màu do alpha). */
  cardAwaitingTenantQuote: {
    backgroundColor: "#FFFBEB",
    borderWidth: 1,
    borderColor: "rgba(217, 119, 6, 0.38)",
    shadowColor: "rgba(180, 83, 9, 0.14)",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 3,
  },
  cardTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 12,
  },
  cardTopRowRight: {
    flex: 1,
    minWidth: 0,
    alignItems: "flex-end",
  },
  statusPillTop: {
    alignSelf: "flex-end",
    maxWidth: "100%",
  },
  /**
   * Nhãn loại ticket — màu nhận diện rõ: sửa chữa xanh lá, hỏi đáp xanh biển, bảo trì cam đất.
   */
  typeTag: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 6,
    marginBottom: 12,
  },
  typeTagInRow: {
    marginBottom: 0,
    flexShrink: 0,
  },
  typeTagText: {
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.2,
  },
  typeRepair: {
    backgroundColor: brandTintBg,
    borderWidth: 1,
    borderColor: "rgba(59, 181, 130, 0.4)",
  },
  typeRepairText: {
    color: "#047857",
    fontWeight: "700",
  },
  typeQuestion: {
    backgroundColor: brandBlueMutedBg,
    borderWidth: 1,
    borderColor: brandBlueMutedBorder,
  },
  typeQuestionText: {
    color: "#0369A1",
    fontWeight: "700",
  },
  typeMaintenance: {
    backgroundColor: "rgba(217, 119, 6, 0.14)",
    borderWidth: 1,
    borderColor: "rgba(217, 119, 6, 0.4)",
  },
  typeMaintenanceText: {
    color: "#B45309",
    fontWeight: "700",
  },
  typeDefault: {
    backgroundColor: neutral.tileMuted,
    borderWidth: 1,
    borderColor: neutral.border,
  },
  typeDefaultText: {
    color: neutral.slate500,
    fontWeight: "600",
  },
  rowTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: neutral.text,
    marginBottom: 8,
    lineHeight: 22,
  },
  dateRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 12,
  },
  paymentCallout: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: "rgba(245, 158, 11, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(245, 158, 11, 0.28)",
    marginBottom: 12,
  },
  paymentCalloutText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "600",
    color: "#92400E",
  },
  payBtnFull: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: brandPrimary,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 6,
    shadowColor: brandPrimary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.22,
    shadowRadius: 4,
    elevation: 4,
  },
  payBtnFullText: {
    fontSize: 15,
    fontWeight: "800",
    color: neutral.surface,
  },
  /** Ticket QUESTION đã có phản hồi — mở TenantQuestionDetail. */
  questionAnswerBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 12,
    backgroundColor: neutral.surface,
    borderWidth: 1.5,
    borderColor: brandSecondary,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  questionAnswerBtnText: {
    flex: 1,
    fontSize: 15,
    fontWeight: "700",
    color: brandSecondary,
  },
  detailLinkCenter: {
    alignSelf: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  dateLine: {
    fontSize: 12,
    color: neutral.textMuted,
  },
  cardBottomRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 12,
  },
  /** Trạng thái: pill + chấm màu nhạt. */
  statusPill: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    flexShrink: 1,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginRight: 8,
  },
  statusPillText: {
    fontSize: 12,
    fontWeight: "600",
    flexShrink: 1,
  },
  statusCreated: {
    backgroundColor: "#F1F5F9",
  },
  statusCreatedDot: {
    backgroundColor: "#CBD5E1",
  },
  statusCreatedText: {
    color: "#64748B",
  },
  /** Nổi bật: Chờ người thuê duyệt */
  statusWaitingTenant: {
    backgroundColor: "#FFF7ED",
  },
  statusWaitingTenantDot: {
    backgroundColor: "#F59E0B",
  },
  statusWaitingTenantText: {
    color: "#92400E",
  },
  /** Chờ thanh toán — tách biệt khỏi “đã gửi” để user quét nhanh. */
  statusWaitingPayment: {
    backgroundColor: "rgba(245, 158, 11, 0.16)",
  },
  statusWaitingPaymentDot: {
    backgroundColor: "#D97706",
  },
  statusWaitingPaymentText: {
    color: "#92400E",
  },
  statusScheduled: {
    backgroundColor: "#EEF6FB",
  },
  statusScheduledDot: {
    backgroundColor: "#7EB8D8",
  },
  statusScheduledText: {
    color: "#52606D",
  },
  statusInProgress: {
    backgroundColor: "#E8F4FA",
  },
  statusInProgressDot: {
    backgroundColor: "#5BA3C6",
  },
  statusInProgressText: {
    color: "#4A6572",
  },
  statusDone: {
    backgroundColor: "#F0FDF4",
  },
  statusDoneDot: {
    backgroundColor: "#86EFAC",
  },
  statusDoneText: {
    color: "#4B5563",
  },
  statusCancelled: {
    backgroundColor: "#FEF2F2",
  },
  statusCancelledDot: {
    backgroundColor: "#FCA5A5",
  },
  statusCancelledText: {
    color: "#9CA3AF",
  },
  statusDefault: {
    backgroundColor: neutral.backgroundSubtle,
  },
  statusDefaultDot: {
    backgroundColor: neutral.slate300,
  },
  statusDefaultText: {
    color: neutral.textSecondary,
  },
  detailsBtn: {
    flexDirection: "row",
    alignItems: "center",
    flexShrink: 0,
  },
  detailsText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#3D8BA8",
  },
  payBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    backgroundColor: brandSecondary,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: brandSecondary,
  },
  payText: {
    fontSize: 12,
    fontWeight: "800",
    color: neutral.surface,
    marginRight: 6,
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  hint: {
    marginTop: 14,
    ...appTypography.body,
    color: neutral.textSecondary,
  },
  errorText: {
    ...appTypography.body,
    color: neutral.textSecondary,
    textAlign: "center",
    marginBottom: 18,
    lineHeight: 22,
  },
  retryBtn: {
    backgroundColor: brandSecondary,
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 12,
    minWidth: 160,
    alignItems: "center",
    shadowColor: brandSecondary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    elevation: 3,
  },
  retryBtnText: {
    ...appTypography.dialogButton,
    color: neutral.surface,
    fontWeight: "600",
  },
  empty: {
    ...appTypography.body,
    color: neutral.textMuted,
    textAlign: "center",
    paddingVertical: 40,
    paddingHorizontal: 24,
    lineHeight: 22,
  },
});

/** Màn chi tiết ticket tenant — thẻ tròn, header icon như mockup Figma. */
export const tenantTicketDetailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: neutral.canvasMuted,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 32,
    gap: 16,
  },
  /** Thẻ section: icon xanh + nhãn IN HOA trong card (MÔ TẢ / ẢNH / THANH TOÁN). */
  detailCard: {
    backgroundColor: neutral.surface,
    borderRadius: 20,
    padding: 18,
    shadowColor: neutral.slate900,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
  },
  detailCardHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 4,
  },
  detailCardHeaderLabel: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.9,
    color: neutral.textMuted,
    textTransform: "uppercase",
    flex: 1,
  },
  detailFieldRow: {
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth * 2,
    borderBottomColor: neutral.borderMuted ?? neutral.border,
  },
  detailFieldRowLast: {
    borderBottomWidth: 0,
    paddingBottom: 4,
  },
  paymentLineRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 10,
  },
  paymentLineName: {
    flex: 1,
    fontSize: 15,
    fontWeight: "600",
    color: neutral.text,
    lineHeight: 22,
  },
  paymentLinePrice: {
    fontSize: 15,
    fontWeight: "700",
    color: neutral.text,
    textAlign: "right",
  },
  paymentDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: neutral.border,
    marginTop: 4,
    marginBottom: 8,
  },
  paymentTotalRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 2,
  },
  paymentTotalLabel: {
    fontSize: 16,
    fontWeight: "700",
    color: neutral.text,
  },
  paymentTotalValue: {
    fontSize: 20,
    fontWeight: "800",
    color: brandPrimary,
    letterSpacing: -0.2,
  },
  payNowBtn: {
    marginTop: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: brandPrimary,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 16,
    shadowColor: brandPrimary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.22,
    shadowRadius: 4,
    elevation: 5,
  },
  payNowBtnText: {
    color: neutral.surface,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "800",
  },
  heroCard: {
    backgroundColor: neutral.surface,
    borderRadius: 20,
    padding: 18,
    borderWidth: 0,
    shadowColor: neutral.slate900,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
  },
  heroTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: neutral.text,
    lineHeight: 26,
    marginBottom: 12,
  },
  badgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  heroDateRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  heroDateText: {
    fontSize: 13,
    color: neutral.textMuted,
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.6,
    color: neutral.textMuted,
    textTransform: "uppercase",
    marginBottom: 8,
    marginLeft: 2,
  },
  /** Giữ tên `panel` cho đoạn code cũ; ưu tiên `detailCard` trên màn chi tiết. */
  panel: {
    backgroundColor: neutral.surface,
    borderRadius: 20,
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderWidth: 0,
    shadowColor: neutral.slate900,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
  },
  panelRow: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: neutral.borderMuted,
  },
  panelRowLast: {
    borderBottomWidth: 0,
  },
  fieldLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: neutral.textMuted,
    marginBottom: 4,
  },
  fieldValue: {
    fontSize: 15,
    fontWeight: "500",
    color: neutral.text,
    lineHeight: 22,
  },
  fieldValueMuted: {
    fontSize: 14,
    fontWeight: "400",
    color: neutral.textSecondary,
    fontStyle: "italic",
  },
  fieldValueMono: {
    fontSize: 12,
    fontWeight: "500",
    color: neutral.slate600,
    lineHeight: 18,
  },
  fieldValuePhone: {
    ...appTypography.modalListItem,
    fontWeight: "700",
    color: neutral.text,
    lineHeight: 22,
  },
  quoteItemName: {
    fontSize: 14,
    fontWeight: "600",
    color: neutral.text,
    flex: 1,
  },
  quoteItemPrice: {
    fontSize: 14,
    fontWeight: "700",
    color: neutral.text,
    textAlign: "right",
    marginLeft: 12,
  },
  quoteTotalRow: {
    paddingTop: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  quoteTotalLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: neutral.textMuted,
  },
  quoteTotalValue: {
    fontSize: 16,
    fontWeight: "800",
    color: brandPrimary,
  },
  confirmQuoteBtn: {
    marginTop: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: brandPrimary,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 16,
    shadowColor: brandPrimary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.22,
    shadowRadius: 4,
    elevation: 5,
  },
  confirmQuoteBtnText: {
    color: neutral.surface,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "800",
  },
  assetLoadingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  descriptionBody: {
    fontSize: 15,
    lineHeight: 24,
    color: neutral.text,
    paddingTop: 10,
    paddingBottom: 4,
  },
  /** Chờ duyệt báo giá — mô tả ngắn ngay trong card Báo giá. */
  quoteAwaitingTenantIntro: {
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "500",
    color: "#92400E",
    marginTop: 6,
    marginBottom: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: "rgba(255, 251, 235, 0.96)",
    borderWidth: 1,
    borderColor: "rgba(217, 119, 6, 0.35)",
  },
  ticketImagesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 4,
  },
  ticketImagesScroll: {
    maxHeight: 240,
  },
  ticketImagesStrip: {
    flexDirection: "row",
    gap: 12,
    paddingTop: 10,
    paddingBottom: 4,
  },
  ticketImageThumb: {
    width: "48%",
    aspectRatio: 1,
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 0,
    backgroundColor: neutral.canvasMuted,
  },
  ticketImageThumbHorizontal: {
    width: 150,
    aspectRatio: 1,
    borderRadius: 16,
  },
  /** Một ảnh duy nhất — full width trong card giống mockup. */
  ticketImageThumbFull: {
    width: "100%",
    aspectRatio: 16 / 11,
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: neutral.canvasMuted,
  },
  ticketImage: {
    width: "100%",
    height: "100%",
  },
  ticketImagesMoreBtn: {
    marginTop: 6,
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: neutral.border,
    backgroundColor: neutral.canvasMuted,
  },
  ticketImagesMoreBtnText: {
    fontSize: 12,
    fontWeight: "600",
    color: neutral.textSecondary,
  },
  ticketImagesEmpty: {
    paddingVertical: 12,
    paddingHorizontal: 4,
  },
  imageModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(2, 6, 23, 0.85)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    position: "relative",
  },
  imageModalBackdropDismiss: {
    ...StyleSheet.absoluteFillObject,
  },
  imageModalPager: {
    width: "100%",
    height: 320,
  },
  imageModalContent: {
    width: "100%",
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: neutral.borderMuted ?? neutral.border,
    backgroundColor: neutral.surface,
    zIndex: 1,
  },
  imageModalClose: {
    position: "absolute",
    top: 10,
    right: 10,
    zIndex: 2,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(15, 23, 42, 0.75)",
  },
  imageModalCloseText: {
    color: neutral.surface,
    fontSize: 18,
    fontWeight: "800",
    lineHeight: 20,
  },
  imageModalImage: {
    width: "100%",
    height: 320,
  },
});
