import { StyleSheet } from "react-native";
import {
  BRAND_DANGER,
  brandBlueMutedBg,
  brandBlueMutedBorder,
  brandPrimary,
  brandSecondary,
  brandTintBg,
  neutral,
} from "../../../../shared/theme/color";
import { appTypography } from "../../../../shared/utils";

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: neutral.canvasMuted },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: neutral.border,
  },
  back: { ...appTypography.body, color: brandPrimary },
  title: { ...appTypography.screenHeader, color: neutral.heading },
  body: { flex: 1 },
  web: { height: 420, marginTop: 12 },
  loadingWrap: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "center",
    alignItems: "center",
  },
  placeholder: { padding: 24, justifyContent: "center" },
  placeholderTitle: {
    ...appTypography.sectionHeading,
    fontWeight: "600",
    marginBottom: 12,
    color: neutral.heading,
  },
  placeholderBody: { ...appTypography.body, lineHeight: 22, color: neutral.textSecondary },
  invoiceId: {
    marginTop: 20,
    ...appTypography.caption,
    fontFamily: "monospace",
    color: neutral.textSecondary,
  },
  checklistCard: {
    marginTop: 16,
    marginHorizontal: 16,
    padding: 16,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: neutral.border,
    backgroundColor: neutral.surface,
  },
  checklistTitle: {
    ...appTypography.sectionHeading,
    fontWeight: "600",
    color: neutral.heading,
    marginBottom: 8,
  },
  checklistSubTitle: {
    ...appTypography.body,
    color: neutral.textSecondary,
    marginBottom: 12,
    lineHeight: 22,
  },
  selectAllRow: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: neutral.border,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 12,
    gap: 8,
    backgroundColor: neutral.surface,
  },
  selectAllText: {
    ...appTypography.body,
    color: neutral.text,
    fontWeight: "600",
    flex: 1,
  },
  selectAllMeta: {
    ...appTypography.caption,
    color: neutral.textSecondary,
  },
  invoiceRow: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "flex-start",
    paddingVertical: 6,
  },
  checkbox: { width: 26, fontSize: 18, color: brandPrimary },
  invoiceText: { ...appTypography.body, flex: 1, color: neutral.textSecondary },
  invoiceTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  invoiceMetaText: {
    ...appTypography.caption,
    color: neutral.textMuted,
    marginTop: 2,
  },
  invoiceAmountText: {
    ...appTypography.sectionHeading,
    color: brandPrimary,
    marginTop: 6,
  },
  invoiceAccordionCard: {
    borderWidth: 1,
    borderColor: brandBlueMutedBorder,
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    backgroundColor: brandTintBg,
  },
  invoiceAccordionHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 4,
  },
  accordionChevronBtn: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  invoiceAccordionBody: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: neutral.border,
  },
  typeBadge: {
    alignSelf: "flex-start",
    backgroundColor: brandBlueMutedBg,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
    marginBottom: 6,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: brandBlueMutedBorder,
  },
  typeBadgeText: {
    ...appTypography.caption,
    color: brandSecondary,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  totalLabel: {
    ...appTypography.caption,
    color: neutral.textBody,
    fontWeight: "700",
    marginTop: 4,
  },
  amountRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  amountAction: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: neutral.surface,
    borderWidth: 1,
    borderColor: brandBlueMutedBorder,
  },
  checkboxRound: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: neutral.slate400,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  checkboxRoundOn: {
    borderColor: brandPrimary,
    backgroundColor: brandPrimary,
  },
  selectedCount: { ...appTypography.caption, marginTop: 8, color: neutral.textMuted },
  paginationWrap: { paddingBottom: 0, paddingTop: 10 },
  payButton: {
    marginTop: 14,
    marginHorizontal: 16,
    borderRadius: 12,
    backgroundColor: brandPrimary,
    paddingVertical: 15,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    gap: 10,
  },
  payButtonDisabled: {
    opacity: 0.45,
  },
  payButtonText: { ...appTypography.body, color: neutral.surface, fontWeight: "700" },
  infoCard: {
    marginHorizontal: 16,
    marginTop: 12,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: neutral.border,
    backgroundColor: neutral.surface,
    padding: 16,
  },
  linkErrorText: {
    marginHorizontal: 16,
    marginTop: 12,
    color: BRAND_DANGER,
  },
});

export default styles;
