import { StyleSheet } from "react-native";
import {
  brandDangerBg,
  brandDangerBorder,
  brandFocusBorder,
  brandPrimary,
  brandSecondary,
  brandTintBg,
  iotOfflineLabelColor,
  neutral,
  tenantInvoicePaidBadgeBg,
  tenantInvoicePaidBadgeFg,
  tenantInvoiceUnpaidBadgeBg,
  tenantInvoiceUnpaidBadgeFg,
} from "../../../../shared/theme/color";
import { appTypography } from "../../../../shared/utils/typography";

export const tenantInvoiceStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: neutral.background,
  },
  pageHeading: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 6,
  },
  pageTitle: {
    ...appTypography.ticketScreenTitle,
    fontSize: 22,
    color: neutral.heading,
    marginBottom: 6,
  },
  pageSubtitle: {
    fontSize: 13,
    lineHeight: 18,
    color: neutral.textMuted,
  },
  selectAllRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: neutral.backgroundElevated,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: neutral.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginTop: 14,
    marginBottom: 4,
    gap: 10,
  },
  selectAllText: {
    ...appTypography.body,
    color: neutral.text,
    fontWeight: "600",
    flex: 1,
  },
  selectAllMeta: {
    ...appTypography.caption,
    color: neutral.textSecondary,
  },
  houseChipScroll: {
    flexGrow: 0,
    marginTop: 10,
    marginHorizontal: -4,
  },
  houseChipScrollContent: {
    paddingHorizontal: 16,
    gap: 8,
    paddingVertical: 2,
    flexDirection: "row",
    alignItems: "center",
  },
  houseChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: neutral.backgroundElevated,
    borderWidth: 1,
    borderColor: neutral.border,
  },
  houseChipActive: {
    backgroundColor: brandTintBg,
    borderColor: brandFocusBorder,
  },
  houseChipText: {
    ...appTypography.caption,
    fontWeight: "600",
    color: neutral.textSecondary,
  },
  houseChipTextActive: {
    color: brandPrimary,
  },
  cardHouseLine: {
    ...appTypography.caption,
    color: neutral.textMuted,
    marginBottom: 6,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 18,
    marginBottom: 10,
    gap: 8,
  },
  sectionHeaderRowFirst: {
    marginTop: 4,
  },
  sectionAccent: {
    width: 4,
    height: 18,
    borderRadius: 2,
    backgroundColor: neutral.slate400,
  },
  sectionTitle: {
    ...appTypography.sectionHeading,
    fontWeight: "700",
    color: neutral.heading,
  },
  listContent: {
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 24,
    gap: 10,
  },
  listEmptyGrow: {
    flexGrow: 1,
    justifyContent: "center",
  },
  emptyText: {
    textAlign: "center",
    ...appTypography.body,
    color: neutral.textMuted,
    paddingHorizontal: 24,
  },
  card: {
    backgroundColor: neutral.surface,
    borderRadius: 14,
    padding: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: neutral.slate200,
    shadowColor: neutral.slate900,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  cardTopRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    gap: 8,
  },
  cardTopRowSpacer: {
    flex: 1,
    minWidth: 8,
  },
  statusPill: {
    flexShrink: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
  },
  statusPillText: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  statusUnpaid: { backgroundColor: tenantInvoiceUnpaidBadgeBg },
  statusUnpaidText: { color: tenantInvoiceUnpaidBadgeFg },
  statusPaid: { backgroundColor: tenantInvoicePaidBadgeBg },
  statusPaidText: { color: tenantInvoicePaidBadgeFg },
  rowTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: neutral.text,
    marginBottom: 6,
    lineHeight: 21,
    textTransform: "uppercase",
  },
  amount: {
    fontSize: 20,
    fontWeight: "700",
    color: neutral.heading,
    textAlign: "right",
    marginTop: 4,
  },
  dueRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  meta: {
    ...appTypography.caption,
    fontSize: 13,
    color: neutral.textSecondary,
    flex: 1,
    minWidth: 0,
  },
  detailsLink: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  detailsLinkText: {
    fontSize: 14,
    fontWeight: "600",
    color: brandSecondary,
  },
  contentScroll: {
    flex: 1,
  },
  contentContainer: {
    paddingHorizontal: 20,
    paddingBottom: 32,
  },
  detailCard: {
    backgroundColor: neutral.surface,
    borderRadius: 14,
    padding: 16,
    marginTop: 16,
    borderWidth: 1,
    borderColor: neutral.border,
  },
  detailLabel: {
    ...appTypography.labelRow,
    color: neutral.textSecondary,
    marginTop: 10,
  },
  detailValue: {
    ...appTypography.modalListItem,
    color: neutral.text,
    marginTop: 4,
  },
  payButton: {
    marginTop: 24,
    backgroundColor: brandPrimary,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
  },
  payButtonText: {
    ...appTypography.dialogButton,
    color: neutral.surface,
    fontWeight: "700",
  },
  payButtonDisabled: {
    opacity: 0.5,
  },
  detailSummaryBlock: {
    alignItems: "center",
    paddingTop: 8,
    paddingBottom: 20,
    paddingHorizontal: 8,
  },
  detailStatusPill: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 999,
    marginBottom: 12,
  },
  detailStatusPillText: {
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  detailStatusUnpaidBg: {
    backgroundColor: brandDangerBg,
  },
  detailStatusUnpaidText: {
    color: iotOfflineLabelColor,
  },
  detailStatusPaidBg: {
    backgroundColor: tenantInvoicePaidBadgeBg,
  },
  detailStatusPaidText: {
    color: tenantInvoicePaidBadgeFg,
  },
  detailInvoiceCode: {
    fontSize: 14,
    color: neutral.textSecondary,
    textAlign: "center",
    marginBottom: 8,
  },
  detailTotalHero: {
    fontSize: 28,
    fontWeight: "800",
    color: neutral.black,
    textAlign: "center",
    letterSpacing: -0.5,
  },
  detailTimelineCard: {
    backgroundColor: neutral.surface,
    borderRadius: 20,
    padding: 18,
    shadowColor: neutral.slate900,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 4,
    marginBottom: 16,
  },
  detailTimelineRow: {
    flexDirection: "row",
  },
  detailTimelineRail: {
    width: 48,
    alignItems: "center",
  },
  detailTimelineIconBoxIssue: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: neutral.slate200,
    alignItems: "center",
    justifyContent: "center",
  },
  detailTimelineIconBoxDue: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: brandDangerBg,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: brandDangerBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  detailTimelineVLine: {
    width: 2,
    height: 28,
    backgroundColor: neutral.slate200,
    marginVertical: 4,
    borderRadius: 1,
  },
  detailTimelineBody: {
    flex: 1,
    paddingLeft: 6,
    gap: 22,
  },
  detailTimelineBlock: {},
  detailTimelineLabel: {
    fontSize: 13,
    color: neutral.textSecondary,
    marginBottom: 4,
  },
  detailTimelineValue: {
    fontSize: 15,
    fontWeight: "700",
    color: neutral.text,
  },
  detailFeeCard: {
    backgroundColor: neutral.surface,
    borderRadius: 20,
    padding: 18,
    marginBottom: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: neutral.border,
  },
  detailFeeCardTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: neutral.heading,
    marginBottom: 14,
  },
  detailFeeRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 10,
  },
  detailFeeRowLabel: {
    flex: 1,
    fontSize: 14,
    color: neutral.textBody,
  },
  detailFeeRowValue: {
    fontSize: 14,
    fontWeight: "600",
    color: neutral.text,
  },
  detailFeeDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: neutral.slate200,
    marginVertical: 6,
  },
  detailFeeTotalRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 4,
  },
  detailFeeTotalLabel: {
    fontSize: 15,
    fontWeight: "800",
    color: neutral.heading,
  },
  detailFeeTotalValue: {
    fontSize: 15,
    fontWeight: "800",
    color: neutral.text,
  },
  detailFooter: {
    paddingHorizontal: 20,
    paddingTop: 12,
    backgroundColor: neutral.surface,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: neutral.border,
  },
  detailPayButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: brandPrimary,
    paddingVertical: 16,
    borderRadius: 18,
    shadowColor: neutral.slate900,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 6,
  },
  detailPayButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: neutral.surface,
  },
  multiFooter: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: neutral.border,
    backgroundColor: neutral.surface,
    shadowColor: neutral.slate900,
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 8,
  },
  multiFooterInner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  multiFooterLeft: {
    flex: 1,
    minWidth: 0,
  },
  multiFooterLabel: {
    ...appTypography.caption,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.6,
    color: neutral.textMuted,
    marginBottom: 4,
  },
  multiSummaryLine: {
    ...appTypography.body,
    flexWrap: "wrap",
  },
  multiSummaryMuted: {
    color: neutral.text,
    fontWeight: "600",
  },
  multiSummaryValue: {
    color: brandPrimary,
    fontWeight: "700",
  },
  multiPayBtn: {
    flexShrink: 0,
    paddingVertical: 13,
    paddingHorizontal: 18,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 148,
    backgroundColor: brandPrimary,
  },
  multiPayBtnDisabled: {
    backgroundColor: neutral.backgroundElevated,
    borderWidth: 1,
    borderColor: neutral.slate200,
  },
  multiPayBtnText: {
    ...appTypography.body,
    color: neutral.surface,
    fontWeight: "700",
    fontSize: 14,
  },
  multiPayBtnTextDisabled: {
    color: neutral.textMuted,
  },
  checkboxRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: neutral.slate400,
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxOn: {
    backgroundColor: brandPrimary,
    borderColor: brandPrimary,
  },
  checkboxRound: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: neutral.slate400,
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxRoundOn: {
    backgroundColor: brandPrimary,
    borderColor: brandPrimary,
  },
  multiCardInner: {
    flex: 1,
    minWidth: 0,
  },
  checkboxHitWrap: {
    paddingVertical: 4,
    paddingRight: 2,
  },
});
